name: Generate README

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache
        uses: actions/cache@v1
        with:
          path: '.'
          key: ${{ runner.os }}-js-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile --check-files
      - name: Generate README
        run: node ./scripts/generate-readme.js
        env:
          CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
          CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
          NODE_ENV: 'production'
      - name: Push new README.md
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
