name: Generate README

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: yarn install --frozen-lockfile --check-files
      - uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: '.'
          key: ${{ github.sha }}

  generate:
    runs-on: ubuntu-latest
    needs: dependencies

    steps:
      - uses: actions/cache@v1
        id: restore-dependencies
        with:
          path: '.'
          key: ${{ github.sha }}
      - name: Generate README
        run: node ./scripts/generate-readme.js
        env:
          CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
          CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
          NODE_ENV: 'production'
      - name: Push new README.md
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
